#!/bin/bash
# By Adam Krivka (aidam38)

cd /home/adam

if [[ ! -d .git/ ]]; then
	echo "Initializing git directory."
	git init
fi

if [[ ! "$(git remote)" =~ "origin" ]]; then
	git remote add origin https://github.com/aidam38/adamos
fi

echo "Commit message: "
read msg

git add .config/ .scripts/ .wallpapers /builds/ .bash_profile .bashrc .fehbg .Xresources README.md .gitconfig .gitmodules
git commit -m "$msg" 
git push origin master
